### ISSUE TITLE
ros-foxy-librealsense2 build crash

### ISSUE THREAD

**Issue by JaehyunShim** [IntelRealSense/librealsense2-release#3]
Hi, 

I install librealsense2 for ROS2 Foxy by the following command input.
$ sudo apt install ros-foxy-librealsense2

The problem is that it needs realsense2 as a dependency but realsense2 does not support Ubuntu 20.04 focal yet.
Any tips?

Ryan

**Comment by MarcoAndrade26** [comment]
@JaehyunShim  Did you installed it?
