### ISSUE TITLE
Release for ROS 2 Galactic

### ISSUE THREAD

**Issue by TSC21** [IntelRealSense/librealsense2-release#4]
@doronhi looking for a `librealsense2` release for Galactic (and maybe even for Rolling). Are you planning to do this with bloom soon? Thanks in advance!

**Comment by doronhi** [comment]
The plan is to release librealsense2 for Galactic along with realsense2_camera. Looking ahead at the schedule it might take a couple of weeks.

**Comment by TSC21** [comment]
> The plan is to release librealsense2 for Galactic along with realsense2_camera. Looking ahead at the schedule it might take a couple of weeks.

Thanks. 2 weeks does seem a long time for something that apparently doesn't require much technical work besides issuing a bloom release. Is there anything that can be done from my side to help speed up the process?

**Comment by markusachtelik** [comment]
Hi @doronhi, this would be highly appreciated, thank you very much :)

**Comment by doronhi** [comment]
Released support for Galactic in realsense2_camera Version 3.2.2.
Debian package awaits merging and synchronization by the rosdistro maintainers. See [#30093](https://github.com/ros/rosdistro/pull/30093)

**Comment by MarcoAndrade26** [comment]
@doronhi Hello! I am new to this! How can I install it on ROS2 Galactic? Thanks!
